name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v1
    - name: Push to GitHub Packages
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: diwms/docker-terraform/docker-terraform
        tag_with_ref: true
